---
name: CI
'on':
  push:
    branches: [ master ]
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@master
        with:
          submodules: false

      - name: Generate and deploy website
        uses: vlegio/hugo-rsync-deployment@v0.0.1
        env:
          VPS_DEPLOY_KEY: ${{secrets.DEPLOY_SSH_KEY}}
          VPS_DEPLOY_USER: ${{secrets.DEPLOY_USER}}
          VPS_DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
          VPS_DEPLOY_DEST: ${{secrets.DEPLOY_TARGET_PATH}}
        with:
          hugo-arguments: '--minify'
          rsync-arguments: '-avz --delete --progress'

      - name: Telegram Notify OK
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_USER_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            **Deploy status**: ✅
            **Project**: `${{github.repository}}`
            **Runs on**: https://github.com/${{github.repository}}/tree/${{github.sha}}
            **Branch**: `${{github.ref}}`
            **Link**: https://vlegio.ru

      - name: Telegram Notify NOK
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_USER_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            **Deploy status**: ❌
            **Project**: `${{github.repository}}`
            **Runs on**: https://github.com/${{github.repository}}/tree/${{github.sha}}
            **Branch**: `${{github.ref}}`
########
# END OF FILE
########
